version: "3.7"
services:
  database:
      image: postgres
      restart: always
      ports: 
        - "4321:5432"
      volumes:
        - /path/to/postgresql-persistence:/bitnami/postgresql
        - ./sql:/docker-entrypoint-initdb.d
      environment:
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=apiclima
  api:
      build: .
      ports: 
        - "4000:3000"
      depends_on:
        - database
      environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432/apiclima
        - port=3000
