--CREATE DATABASE apiclima;

CREATE TABLE IF NOT EXISTS usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    correo text  NOT NULL, 
    password text NOT NULL
);

CREATE TABLE IF NOT EXISTS estaciones (
    id_estacion integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text,
    latitud  text,
    longitud text,
    altura_mar text,
    fecha text,
    precipitacion text,
    temperatura_max text,
    temperatura_min text
    );